apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: order-service:latest
        ports:
        - containerPort: 5001
        imagePullPolicy: Never
