apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: payment-service:latest
        ports:
        - containerPort: 5002
        imagePullPolicy: Never
