# user-deployment-v2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment-v2
  namespace: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      version: v2
  template:
    metadata:
      labels:
        app: user
        version: v2
    spec:
      containers:
      - name: user
        image: v2:latest 
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
