apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment-v1
  namespace: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      version: v1
  template:
    metadata:
      labels:
        app: user
        version: v1
    spec:
      containers:
      - name: user
        image: v1:latest 
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
